---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: {{ include "orakel-of-funk.namespace" . }}
  labels:
    {{- include "orakel-of-funk.valkey.labels" . | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.globalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
        {{- with .Values.globalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.valkey.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: valkey
        image: "{{ .Values.valkey.image.registry }}/{{ .Values.valkey.image.repository }}:{{ .Values.valkey.image.tag  }}"
        imagePullPolicy: {{ .Values.valkey.image.pullPolicy }}
        {{- with .Values.valkey.securityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.valkey.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.valkey.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.valkey.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.valkey.env }}
        env:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: valkey-data
          mountPath: /data
      volumes:
      - name: valkey-data
        {{- if .Values.valkey.storage.enabled }}
        persistentVolumeClaim:
          claimName: valkey-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}