---
apiVersion: v1
kind: Namespace
metadata:
  name: oof-nginx-privileged
  labels:
    app.kubernetes.io/name: oof-nginx-privileged
    app.kubernetes.io/part-of: orakel-of-funk
    app.kubernetes.io/component: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-privileged
  namespace: oof-nginx-privileged
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.29.0
          ports:
            - containerPort: 80
          securityContext: {}
