apiVersion: checks.funk.fhnw.ch/v1alpha1
kind: WorkloadHardeningCheck
metadata:
  name: nginx-privileged
  namespace: oof-nginx-privileged
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-privileged
  baselineDuration: 1m
