---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-checks-funk-fhnw-ch-v1alpha1-workloadhardeningcheck
  failurePolicy: Fail
  name: mworkloadhardeningcheck-v1alpha1.kb.io
  rules:
  - apiGroups:
    - checks.funk.fhnw.ch
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workloadhardeningchecks
  sideEffects: None
