---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orakel-of-funk-manager-role
  labels:
    {{- include "orakel-of-funk.labels" . | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.globalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - checks.funk.fhnw.ch
  resources:
  - workloadhardeningchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - checks.funk.fhnw.ch
  resources:
  - workloadhardeningchecks/finalizers
  verbs:
  - update
- apiGroups:
  - checks.funk.fhnw.ch
  resources:
  - workloadhardeningchecks/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orakel-of-funk-metrics-auth-role
  labels:
    {{- include "orakel-of-funk.labels" . | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.globalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orakel-of-funk-metrics-reader
  labels:
    {{- include "orakel-of-funk.labels" . | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.globalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get