---
apiVersion: v1
kind: Namespace
metadata:
  name: oof-test-chown
  labels:
    app.kubernetes.io/name: oof-test-chown
    app.kubernetes.io/part-of: orakel-of-funk
    app.kubernetes.io/component: test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-chown
  namespace: oof-test-chown
  labels:
    app.kubernetes.io/part-of: orakel-of-funk
    app.kubernetes.io/component: test
data:
  test_chown: |
    #! /bin/bash
    set -u # Treat unset variables as an error
    set -o pipefail # Fail on any command in a pipeline that fails

    # Try to chown an existing file
    if [ "$#" -ne 2 ]; then
        echo "Usage: $0 <file_path> <uid:gid>"
        exit 1
    fi

    FILE_PATH="$1"
    # Check if the file exists
    if [ ! -f "$FILE_PATH" ]; then
      touch "$FILE_PATH" # Create the file if it does not exist
      echo "[$( date --rfc-3339=s)] File $FILE_PATH did not exist, created it."
    else  
      echo "[$( date --rfc-3339=s)] File $FILE_PATH exists, proceeding to change ownership."
    fi

    while true
    do
      # Try to change the ownership of the file
      chown -v ${2} "$FILE_PATH" 
      if [ $? -eq 0 ]; then
        echo "[$( date --rfc-3339=s)] Ownership of $FILE_PATH changed to root:root successfully."
      else
        echo "[$( date --rfc-3339=s)] Error: Failed to change ownership of $FILE_PATH"
      fi

      sleep 5 # Sleep for 5 seconds before the next attempt
    done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-chown
    app.kubernetes.io/part-of: orakel-of-funk
    app.kubernetes.io/component: test
  name: test-chown
  namespace: oof-test-chown
spec:
  selector:
    matchLabels:
      app: test-chown
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: test-chown
    spec:
      containers:
        - name: test-chown
          image: docker.io/debian:bookworm
          command:
            - "test_chown"
            - "/tmp/bla"
            - "33:33" # Change ownership to 33:33 (www-data:www-data)
          securityContext: {}
          volumeMounts:
            - name: test-chown
              mountPath: /usr/local/bin/test_chown
              subPath: test_chown
              readOnly: true
            - name: tmp
              mountPath: /tmp/
      volumes:
        - name: test-chown
          configMap:
            name: test-chown
            defaultMode: 0777
        - name: tmp
          emptyDir: {}
---
apiVersion: checks.funk.fhnw.ch/v1alpha1
kind: WorkloadHardeningCheck
metadata:
  name: test-chown
  namespace: oof-test-chown
  labels:
    app.kubernetes.io/part-of: orakel-of-funk
    app.kubernetes.io/component: test
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-chown
  recordingDuration: 1m