# This rule is not used by the project orakel-of-funk itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to checks.funk.fhnw.ch resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: orakel-of-funk
    app.kubernetes.io/managed-by: kustomize
  name: namespacehardeningcheck-viewer-role
rules:
- apiGroups:
  - checks.funk.fhnw.ch
  resources:
  - namespacehardeningchecks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - checks.funk.fhnw.ch
  resources:
  - namespacehardeningchecks/status
  verbs:
  - get
