---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - checks.funk.fhnw.ch
  resources:
  - namespacehardeningchecks
  - workloadhardeningchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - checks.funk.fhnw.ch
  resources:
  - namespacehardeningchecks/finalizers
  - workloadhardeningchecks/finalizers
  verbs:
  - update
- apiGroups:
  - checks.funk.fhnw.ch
  resources:
  - namespacehardeningchecks/status
  - workloadhardeningchecks/status
  verbs:
  - get
  - patch
  - update
