apiVersion: v1
kind: Namespace
metadata:
  labels:
    {{- include "orakel-of-funk.labels" . | nindent 4 }}
    {{- with .Values.globalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.globalAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "orakel-of-funk.namespace" . }}
  