apiVersion: checks.funk.fhnw.ch/v1alpha1
kind: WorkloadHardeningCheck
metadata:
  labels:
    app.kubernetes.io/name: orakel-of-funk
    app.kubernetes.io/managed-by: kustomize
  name: workloadhardeningcheck-sample
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-node
