---
apiVersion: v1
kind: Namespace
metadata:
  name: oof-nginx-unprivileged-tmp-dir
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-unprivileged-tmp-dir
  namespace: oof-nginx-unprivileged-tmp-dir
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:1.29.0
          ports:
            - containerPort: 8080
          securityContext: {}
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}
