---
apiVersion: v1
kind: Namespace
metadata:
  name: oof-nginx-unprivileged-tmp-dir
  labels:
    app.kubernetes.io/name: oof-nginx-unprivileged-tmp-dir
    app.kubernetes.io/part-of: orakel-of-funk
    app.kubernetes.io/component: test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: oof-nginx-unprivileged-tmp-dir
data:
  nginx.conf: |
    worker_processes  auto;

    error_log  /tmp/error.log warn;
    pid        /tmp/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      proxy_temp_path /tmp/proxy_temp;
      client_body_temp_path /tmp/client_temp;
      fastcgi_temp_path /tmp/fastcgi_temp;
      uwsgi_temp_path /tmp/uwsgi_temp;
      scgi_temp_path /tmp/scgi_temp;

      server {
        listen 8080;
        location / {
          add_header Content-Type text/plain;
          return 200 'hello world';
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-unprivileged-tmp-dir
  namespace: oof-nginx-unprivileged-tmp-dir
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.29.0
          ports:
            - containerPort: 8080
          securityContext: {}
          volumeMounts:
            - name: cache
              mountPath: /var/cache/nginx
            - name: tmp
              mountPath: /tmp/
            - name: conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: cache
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: conf
          configMap:
            name: nginx-conf
