apiVersion: checks.funk.fhnw.ch/v1alpha1
kind: WorkloadHardeningCheck
metadata:
  name: nginx-unprivileged-tmp-dir
  namespace: oof-nginx-unprivileged-tmp-dir
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-unprivileged-tmp-dir
  securityContext:
    pod:
      runAsUser: 101
      runAsGroup: 101
      fsGroup: 101
    container:
      runAsUser: 101
      runAsGroup: 101
  baselineDuration: 1m
