apiVersion: v2
name: orakel-of-funk
description: Keep your Kubernetes workloads in tune — secure and functional.
type: application
icon: https://raw.githubusercontent.com/fhnw-imvs/fhnw-kubeseccontext/refs/heads/main/docs/images/orakel-of-funk-logo-small.png
keywords:
  - security
  - compliance
  - securityContext
  - hardening

maintainers:
  - name: Mathias Petermann
    email: mathias.petermann@students.fhnw.ch
    url: https://github.com/peschmae

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.6.3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.6.3"

annotations:
  artifacthub.io/category: security
  artifacthub.io/license: Apache-2.0
  artifacthub.io/crds: |
    - kind: WorkloadHardeningCheck
      version: v1alpha1
      name: WorkloadHardeningCheck
      displayName: Workload Hardening Check
      description: Runs multiple checks to recommend a secure and functional security context for a Kubernetes workload.
    - kind: NamespaceHardeningCheck
      version: v1alpha1
      name: NamespaceHardeningCheck
      displayName: Namespace Hardening Check
      description: Creates WorkloadHardeningChecks for all workloads in a namespace to recommend a secure and functional security context.
  artifacthub.io/crdsExamples: |
    - kind: WorkloadHardeningCheck
      apiVersion: checks.funk.fhnw.ch/v1alpha1
      metadata:
        name: example-workload-hardening-check
        namespace: default
      spec:
        targetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: example-deployment
        recordingDuration: 5m
        runMode: paralell
        suffix: optional-suffix
    - kind: NamespaceHardeningCheck
      apiVersion: checks.funk.fhnw.ch/v1alpha1
      metadata:
        name: example-namespace-hardening-check
      spec:
        targetNamespace: default
        recordingDuration: 5m
        runMode: paralell
        suffix: optional-suffix
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
  artifacthub.io/operator: "true"
