name: Release Charts

on:
  push:
    branches: ['main']
    tags:
      - '*.*.*'

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: read
      packages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Helm OCI Chart Releaser
        uses: appany/helm-oci-chart-releaser@v0.5.0
        with:
          name: orakel-of-funk
          repository: fhnw-imvs/fhnw-kubeseccontext
          tag: 0.1.0
          path: deploy/charts/orakel-of-funk
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          sign: false